apiVersion: apps/v1

kind: StatefulSet

metadata:
  name: my-app

spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      containers:
        - name: my-app
          image: demo:1.0
          ports:
            - containerPort: 8088
